name: convo-app

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    ports:
      - "5173:80" # Map frontend to port 3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    ports:
      - "3000:5173" # Map backend to port 5000
    environment:
      - NODE_ENV=production